name: Android CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Run unit tests
        working-directory: android
        run: ./gradlew :core:test